config/routes.rb
Rails.application.routes.draw do

  resources :campers

  devise_for :users

  resources :users

  root 'campers#leaderboard'

  get '/about', to: 'static_pages#about'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camper.rb
class Camper < ApplicationRecord
  belongs_to :user , optional: true

  before_save { username.downcase! }

  validates :username, presence: true, length: { maximum: 100 },
                    uniqueness: { case_sensitive: false }

  def self.no_user
    Camper.includes(:user).where(users: {id: nil})
  end

  def fcc_url
    "https://www.freecodecamp.com/#{self.username}"
  end
end

app/models/camper_profile.rb
class CamperProfile < ApplicationRecord
  belongs_to :user , optional: true

  def self.no_user
    CamperProfile.includes(:user).where(users: {id: nil})
  end

  def fcc_url
    "https://www.freecodecamp.com/#{self.username}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :camper

  before_save { email.downcase! }
  enum role: [:guest, :user, :admin, :master]
  after_initialize :set_default_role, :if => :new_record?
  accepts_nested_attributes_for :camper
  # validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.no_camper
    User.includes(:camper).where(campers: {id: nil})
  end

  def fcc_username
    camper.username if camper
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  #after_action :verify_authorized, except: :index


   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up) do |user_params|
       user_params.permit({ roles: [] }, :email, :password, :password_confirmation)
     end
   end
end

app/controllers/campers_controller.rb
class CampersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

    def index
      @campers = Camper.all
    end

    def show
      find_camper
    end

    def new
      @camper = Camper.new
    end

    def create
      @camper = Camper.create(camper_params)
      redirect_to camper_path(@camper)
    end

    def edit
      find_camper
    end

    def update
      find_camper
      @camper.update(camper_params)
      redirect_to attraction_path(@attraction)
    end

    private

    def camper_params
      params.require(:camper).permit(:username, :points, :user_id)
    end

    def find_camper
      @camper = Camper.find_by(id: params[:id])
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:leaderboard, :about]

  def leaderboard
  end

  def about
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  #after_action :verify_authorized
  ## I shouldn't have to add authorize to every method yea?
  def new
    @user = User.new
    @user.camper = Camper.new
  end

  def create
  end

  def index
    @users = User.all
  end

  def show
    find_user
  end

  def update
    find_user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    find_user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def secure_params
    params.require(:user).permit(:role, :fcc_username, :bio, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campers_helper.rb
module CampersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/campers/_camper.html.erb
<td>
  1
</td>
<td>
  <%=image_tag("no-face.png",  width: '50', alt: "No face camper with laptop")%>
</td>
<td>
  <span><%= link_to camper.username, camper.fcc_url, :target => "_blank" %></span>
</td>

<td>
  <%=camper.points || "0"%>
</td>

<%if current_user.try(:admin?)%>
  <td>
    <%= link_to("Edit", edit_camper_path(camper), :class => 'button-xs btn-primary') unless camper.user == current_user %>
  </td>
  <td>
    <%= link_to("Delete", camper_path(camper), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs btn-danger') unless camper.user == current_user %>
  </td>
<%end%>

app/views/campers/edit.html.erb
<%if camper.user%>
  <p>Associated User: <%= link_to camper.user.email, user_path(camper.user) %></p>
<%end%>
</td>
<td>
  <%= form_for camper, controller: 'attractions', action: 'update' do |f| %>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <%unless camper.user%>
      <div class="form-group">
        <%= f.label :user, "Select Associated User Account" %>
        <%= f.collection_select :user_id, User.no_camper, :id, :email, :include_blank => true %>
      </div>
    <%end%>

    <div class="actions form-group">
      <%= f.submit "Update Camper Profile", :class => 'btn btn-primary' %>
    </div>

  <% end %>

app/views/campers/index.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Free Code Camp Fargo, ND Leaderboard</h3>
      </div>
      <table class="table table-striped table-responsive">
        <thead>
          <tr>
            <th>#</th>
            <th></th>
            <th>Username</th>
            <th>Points</th>
            <%if current_user.try(:admin?)%>
              <th></th>
              <th></th>
            <%end%>
          </tr>
        </thead>
        <tbody>
          <% @campers.each do |camper| %>
            <tr>
              <%= render camper %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="panel-footer">
        <p>Are you a Free Code Camp member from the Fargo-Moorhead area? <a href="https://goo.gl/forms/3rqXFfCZJ0gHWbmu1", target="_blank">Add your username!</a></p>
      </div>
    </div>
  </div>
</div>

app/views/campers/new.html.erb
<h1>New Free Code Camp Profile</h1>
<%= form_for @camper, controller: 'attractions', action: 'create' do |f| %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>


  <div class="form-group">
    <%= f.label :user, "Select Associated User Account" %>
    <%= f.collection_select :user_id, User.no_camper, :id, :email, :include_blank => true %>
  </div>

  <div class="actions form-group">
    <%= f.submit "Add Camper", :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/campers/show.html.erb
<h1><%= link_to @camper.username, @camper.fcc_url, :target => "_blank" %>'s Free Code Camp Stats</h1>
<ul>
  <li>Overall points: <%=@camper.points%></li>
  <li>Most recent project: <%=link_to "Build a tribute page", "http://codepen.io/kaileeagray/pen/vLqEmz%", :target => "_blank" %></li>
</ul>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Free Code Camp Fargo, ND Leaderboard by <a href="https://github.com/kaileeagray", target="_blank">Kailee Gray</a></small>
  <nav>
    <ul>
      <li><%= render 'layouts/nav_links_for_auth' %></li>
      <li><%= link_to "About", about_path%></li>
      <li><%= link_to "Facebook", "https://www.facebook.com/groups/free.code.camp.fargo/", target: "_blank"%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<!--Rails flash messages styled for Bootstrap 3.0-->
<% flash.each do |name, msg|%>
  <%if msg.is_a?(String)%>
    <div class="alert alert-<%=name.to_s == 'notice' ? 'success' : 'danger'%>">
      <%= content_tag :div, msg, :id => "flash_#{name}"%>
    </div>
  <%end%>
<%end%>

app/views/layouts/_nav_links_for_auth.html.erb
<%if user_signed_in?%>
  <li><%= link_to 'Edit account', edit_user_registration_path%></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method => 'delete'%></li>
<%else%>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<%end%>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-custom">
  <div class="container">
    <%=link_to "Free Code Camp", href="http://www.freecodecamp.com", class: "logo", target: "_blank"%>

    <nav>
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <!-- main nav links -->

      <ul class="nav navbar-nav">
        <li><%= render 'layouts/navigation_links' %></li>
      </ul>

      <!-- social nav links -->

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Join Fargo's campsite!", "https://www.facebook.com/groups/free.code.camp.fargo/", target: "_blank"%></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Fargo Leaderboard', campers_path%></li>
<%if user_signed_in?%>
  <li><%= link_to 'New Camper', new_camper_path%></li>
  <%if current_user.try(:admin?)%>
    <li><%= link_to 'Users', users_path%></li>
  <%end%>
<%end%>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fargo Leaderboard | Free Code Camp</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>

  <body>
      <%= render 'layouts/navigation' %>

    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="center jumbotron">
  <h1>About Leaderboard</h1>

  <h2>  This is a Free Code Camp Fargo leaderboard inspired by <a href="https://www.freecodecamp.com/challenges/build-a-camper-leaderboard">this Free Code Camp challenge</a>. If you are a Free Code Camp Fargo member, add your username via <a href="https://goo.gl/forms/jznuRQj9LEuYjqww2">this survey</a>! Keep working through those challenges to make your way to the top.</h2>

  <%= link_to "Join The Fargo Campsite", "https://www.facebook.com/groups/free.code.camp.fargo/", target: "_blank", class: "btn btn-lg btn-primary"%>
</div>

app/views/static_pages/contact.html.erb
<h1>Contact Us!</h1>
<p>
  <a href="https://www.facebook.com/groups/free.code.camp.fargo/">Message Free Code Camp Fargo, ND here!</a>
</p>

app/views/users/_user.html.erb
<td>
  <%=image_tag("no-face.png",  width: '50', alt: "No face camper with laptop")%>
</td>
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%=user.role%>
</td>
<td>
  <%= link_to edit_user_path(user), class: "button-xs btn-primary", remote: true do %>
    <i class="glyphicon glyphicon-edit"></i>
  <% end %>
</td>
<td>
<div class="form">
  <div class="form-group">
      <%= link_to user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: "button-xs btn-danger", remote: true do %>
        <i class="glyphicon glyphicon-trash"></i>
      <% end %>
  </div>
</div>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Users</h2>
      </div>
      <table class="table table-striped table-responsive">
        <thead>
          <tr>
            <th></th>
            <th>Email</th>
            <th>Role</th>
            <th>Edit user</th>
            <th>Delete user</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>